/**
 * 语言资源文件  中文 zh-CN
 */
// 修复UT问题
if (window.DataViz === undefined) {
  window.DataViz = {};
}
window.DataViz.Language = {
  orderNumber: '序号',

  //slidebar
  createMap: '创建地图',
  userinfo: '账户信息',
  changeskin: '皮肤',
  myMap: '我的地图',
  toIndex: '返回首页',
  toPrev: '返回上一级',
  feedback: '问题反馈',
  lackOfTitle: '无标题',
  baseMap: '底图',
  layerManagement: '图层',
  save: '保存',
  saveAs: '另存为',
  mapSetting: '设置',
  print: '打印',
  loadingData: '正在加载数据...',
  share: '分享',
  packup: '折叠',
  expand: '展开',
  saving: '保存中...',
  updating: '更新中...',
  //底图
  title: '标题',
  baiduMap: '百度地图',
  cloud: '高德地图',
  cloudBlueBlack: '中国蓝黑',
  tencent: '腾讯地图',
  osm: 'OpenStreetMap',
  google: '谷歌地图',
  bing: '必应地图',
  china_dark: '中国暗色地图',
  tianditu_vec_4326: '天地图(经纬度)',
  tianditu_img_4326: '天地图影像(经纬度)',
  tianditu_ter_4326: '天地图地形(经纬度)',
  tianditu_vec_3857: '天地图',
  tianditu_img_3857: '天地图影像',
  tianditu_ter_3857: '天地图地形',
  notConfiguredTiandituKey: "无法使用天地图，请联系管理员添加token",
  tianditu_txt: '天地图_标签',
  customMap: '自定义底图',
  notSupportCRS: '不支持的坐标系',
  getLayerRequestedFailed: '图层信息请求失败，请检查数据源',
  changeWillShift: '自定义底图与当前底图坐标系不同,切换可能导致叠加图层偏移',
  changeBaseMapToDifferent:'当前地图存在叠加图层，不支持切换坐标系不一致的底图',
  japan_std: '日本地理院标准地图',
  japan_pale: '日本地理院淡色地图',
  japan_relief: '日本地理院色别标高地图',
  japan_ort: '日本地理院空中写真地图',
  coordinateSystemInconformity: "当前地图与底图的坐标系不一致，无法添加",
  dynamicProjectionUnable: '当前地图与底图坐标系不一致，且不支持动态投影',
  //layerManager
  drawPointType: '绘制点',
  drawLineType: '绘制线',
  polygonTitle: '绘制面',
  drawRec:'绘制矩形',
  drawHex: '绘制六边形',
  drawCircle:'绘制圆',
  drawEllipse: '绘制椭圆',
  drawBezier: '绘制贝塞尔曲线',
  createMarkerLayer: '创建标注图层',
  //mapsetting
  noneMapTitle: '暂无地图标题',
  label: '标签',
  user: '作者',
  tagPrompt: '（多个标签用逗号隔开，最多6个）',
  description: '描述',
  noneDescription: '暂无描述信息',
  longitude: '经度',
  latitude: '纬度',
  mapLevel: '地图级别',
  mapCenterLevel: '地图中心点和地图级别',
  centerIsWrong: '请输入正确的经纬度',
  levelIsWrong: '请输入正确的地图级别',
  overBaseLayer: '超出当前底图范围',
  mapExtent: '地图范围',
  lbX: '左',
  lbY: '下',
  rtX: '右',
  rtY: '上',
  saveMapType: '默认加载地图范围的方式',
  extentIsWrong: '请输入正确的地图范围',
  saveWithZoom: '使用当前地图中心点和级别',
  saveWithExtent: '使用当前地图范围',
  //modalbox
  okButton: '确定',
  cancelButton: '取消',
  closeButton: '关闭',
  //layermanagement
  addLayer: '添加图层',
  fileUpload: '文件上传',
  emptyFile: '空文件',
  setParams: '指定参数',
  add: '添加',
  uploadFile: '上传文件',
  myData: '我的数据',
  shareData: '与我共享',
  sampleData: '示例数据',
  addByFile: '通过文件添加',
  addByDrag: '或拖拽到这里上传',
  supportFile: '支持 xlsx | xls | csv ，包含表示地理位置的两列，如X | Y，城市名 | 地址。支持GeoJSON以及压缩为Zip的Shapefile数据，需UTF-8编码。目前仅支持坐标系为EPSG:4326、EPSG:3857的数据。',
  nextStep: '下一步',
  prevStep: '上一步',
  createLayer: '创建图层',
  createThemeLayer: '创建专题图层',
  fileProj: '源文件坐标',
  separator: "分隔符",
  inputSeparatorTip: "请输入分隔符",
  baseProj: '底图坐标',
  webMercatorProj: '墨卡托坐标系',
  LonLatProj: '经纬度坐标系',
  posType: '位置类型',
  byCoord: '按坐标',
  byPos: '按地址',
  byDivision: '按行政区划',
  byCoding: '按编码',
  xField: 'X坐标字段',
  yField: 'Y字段坐标',
  cityField: '城市字段',
  addressField: '地址字段',
  divisionType: '行政类别',
  divisionField: '行政字段',
  province: '省份',
  city: '城市',
  district: '区县',
  administrativeCode: '行政代码',
  selectedValue1: "原始值1",
  selectedValue2: "原始值2",
  associationTable: "关联表",
  associationField1: "关联字段1",
  associationField2: "关联字段2",
  zoomTo: '全图',
  output: '导出',
  attributeTable: '属性表',
  rename: '重命名',
  update: '更新',
  updateSuccess: '更新成功',
  autoUpdate: '自动刷新',
  autoUpdateTime: '刷新间隔',
  minutes: '分钟',
  visibleScale: '可见范围',
  maxScaleTips: '最大比例尺不能比最小比例尺小',
  minScaleTips: '最小比例尺不能比最大比例尺大',
  currentScale: '地图当前比例尺',
  maxScale: '最大可见比例尺',
  minScale: '最小可见比例尺',
  level: '第{num}级',
  visibleScaleRange: '可见比例尺范围',
  layerAutoUpdate:'图层自动刷新',
  layerStyle: '图层样式',
  layerArribute: '图层属性',
  fieldCaption: "显示名称",
  show: '显示',
  hide: '隐藏',
  etc: '等',
  filterDatas: '过滤数据{num}条',
  layerLength: '',
  outputType: '格式',
  outputCSVTips: '导出CSV仅保留点数据',
  selectTips: '全选/反选',
  fileName: '文件名',
  noLayerName: '图层名称不能为空',
  layerNameIsExit: '图层名称重复，请重新命名！',
  shareDataNoPermission: '无权限添加',
  overThemeLayerMaxCount: '此数据量过大，无法使用专题图功能',

  //web 添加
  addByWeb: '通过Web添加',
  dataSource: '服务类型',
  serviceUrl: '服务地址',
  proxySetting: '代理配置',
  proxyTooltip: '如果该服务地址不允许跨域访问，请使用代理',
  hasToken: '有令牌',
  noToken: '无令牌',
  token: '令牌',
  hasProxy: '使用代理',
  noProxy: '无代理',
  verifyingDataSource: '正在验证服务地址...',
  restMapRequestFailed: '地图资源请求失败',
  noTileLayer: '服务地址不正确',
  inputToken: '请输入令牌或密钥',
  notRestLayer: '地图资源类型与所选不匹配',
  selectedLayer: '请选择一个图层',
  selectedScales: '请选择一套比例尺',
  wrongEPSGCode: '无法识别数据坐标系',
  urlUnChecked: '不能识别填写的URL',
  scales: '比例尺',
  wmsLayers: '可选图层',
  dpi: 'DPI',
  loadFailed: '获取服务信息失败，请检查服务地址是否符合填写要求或需要令牌',
  addRestMapFailedNoSublayers: '添加地图服务失败，该服务无图层集',
  WMTSUnSupport: '所选比例尺坐标系和底图坐标系不一致，无法添加',
  //web添加 restData
  datasetTable: '数据集表',
  selectAll: '全选',
  unSupport: '暂不支持添加',
  fileType: '类型文件',
  getRestDataFaild: '数据无法访问或不存在',
  featureIsEmpty: '要素为空',
  someFeatureRequestFailed: '部分数据请求失败！',
  //dataflow
  projectionInformation: '坐标系',
  uniqueField: '标识字段',
  uniqueFieldTitile: '指定要素的唯一标识',
  mustUniqueField: '请填写标识字段',
  uniqueFieldIsWrong: '标识字段有误，获取要素失败',
  dataflowUrlIsWrong: '地址输入有误，请检查',
  getDataflowSuccess: '获取数据成功',
  getDataflowFaild: '获取服务失败,请检查服务地址和权限',
  symbolHasDirection: '符号自动旋转',
  directionField: '旋转角度字段',
  rotation: '旋转',
  pathLine: '轨迹线',
  pathPointCount: "轨迹线节点数",
  countUnit: "个",
  pathLineColor: '轨迹线颜色',
  pathLineOpacity: '轨迹线不透明度',
  pathLineWidth: '轨迹线宽度',
  dataflowServiceMete: '未在数据流服务中配置字段信息',
  urlNeedToken: "无法验证地址，请检查输入是否正确或填写令牌",
  setFilterCondition: "设置过滤条件成功，等待过滤结果",
  //标注图层
  defaultMarkerLayer: '未命名标注图层',
  defaultMarkerName: '未命名标注',
  editMarker: '编辑标注',
  deleteMarker: '删除标注',
  deleted: '删除',
  isDeleteFeature: '是否删除标注？',
  deleteServerData: '从我的数据中删除（不可恢复）',
  delteServerDataFaild: '从我的数据删除失败',
  delteServerDataSuccess: '删除成功',
  dataUnexit: '数据不存在或无法访问',
  markerText: '点击编辑文本',
  drawText: '绘制文本',
  customWidth: '自定义(px)',
  width: '宽',
  markerSerchPlaceholder: '输入标题或描述',
  //搜索添加
  addFromSearch: '通过搜索添加',
  myPublicService: '我的服务',
  sampleService: '示例服务',
  publicData: '公众数据',
  industryData: '行业数据',
  natureData: '自然气候数据',
  administrativeData: '行政区划数据',
  position: '位置',
  preview: '预览',
  exitPreview: '退出预览',
  availableService: '可用服务',
  publicService: '发布服务',
  toPulicService: '前往发布',
  serviceName: '服务名称',
  servicePrj: '坐标类型',
  updataTime: '更新时间',
  // projection: '坐标系',
  projection: 'EPSG Code',
  mecator: "墨卡托投影",
  lonlat: "经纬度坐标",
  unSupportCoordinate: '不支持坐标',
  getMyserviceFaild: '请求我的服务失败',
  sendRequest: '请求',
  someDataRequestedFailed: '部分数据信息请求失败',
  dataLoss: '数据丢失',
  addFeatureFaild: '添加失败',
  addToMapFailed: '添加失败,请检查数据是否带有位置信息',
  faild: '失败',
  noLogin: '未登录，请登录以体验更多功能',
  noService: '暂无服务',
  loadingProgress: '已上传',
  addDataSet: '添加数据集',
  loadData: '数据正在加载，已完成{count}/{total}',
  finishLoadDatas: '数据加载完成。共加载{total}条数据，成功{successCount}条，失败{faildCount}条',
  serviceDeleted: '无法操作此服务',
  loginIsInvalid: '登录失效，请重新登录',
  unavailableService: '服务不可用',
  inconsistentWithBaseMap: '与底图坐标系不一致',
  WithoutVisualScale: '超出底图的可见比例尺范围',
  showLayerErrDynamicProjectionNotSupported:'图层显示异常：包含与底图坐标系不一致的图层，且该图层不支持动态投影',
  
  //示例数据
  beijing: '北京',
  allCountry: '全国',
  heilongjiang: '黑龙江',
  jilin: '吉林',
  liaoning: '辽宁',
  xinjiang: '新疆',
  tibet: '西藏',
  qinghai: '青海',
  yunnan: '云南',
  hainan: '海南',
  taiwan: '台湾',
  guangxi: '广西',
  guangdong: '广东',
  guizhou: '贵州',
  sichuan: '四川',
  chongqing: '重庆',
  hunan: '湖南',
  fujian: '福建',
  zhejiang: '浙江',
  shanghai: '上海',
  jiangxi: '江西',
  hubei: '湖北',
  anhui: '安徽',
  jiangsu: '江苏',
  shandong: '山东',
  henan: '河南',
  shanxi: '山西',
  shaanxi: '陕西',
  gansu: '甘肃',
  ningxia: '宁夏',
  tianjin: '天津',
  hebei: '河北',
  innerMongolia: '内蒙古',



  //图层编辑
  layerUnique: '单值',
  layerRange: '分段',
  layerHeat: '热力图',
  layerRankSymbol: '等级符号',
  layerMigration: '迁徙图',
  returnDefaultStyle: '恢复默认样式',
  inquiryReturnDefaultStyle: '专题图层将恢复默认样式，是否继续？',
  returnCustomDefaultStyle: '重置自定义样式',
  inquiryReturnCustomDefaultStyle: '所有自定义样式将恢复为默认设置，是否继续？',
  endEditor: '结束编辑',
  symbolVector: '矢量',
  symbolImage: '图片',
  uploadVector: '自定义',
  pointStyle: '点样式',
  pointColor: '点颜色',
  pointSize: '点大小',
  pointOpacity: '点不透明度',
  lineColor: '线颜色',
  outlineColor: '描边颜色',
  lineStyle: '线样式',
  polygonStyle: '面样式',
  lineOpacity: '线不透明度',
  lineWidth: '线宽度',
  polygonfillColor: '面颜色',
  polygonOpacity: '面不透明度',
  filterCondition: '过滤条件',
  lableField: '显示字段',
  themeField: '专题字段',
  lableStyle: '颜色',
  labelBackgroundColor: "背景色",
  segmentationMethod: '分段方法',
  segmentationQuantity: "分段个数",
  customValue: '自定义单值',
  subsectionMethod: '分段方法',
  segmentsNumber: '分段个数',
  equidistant: '等距分段',
  offsetSegment: '等距分段法',
  natureSegment: '自然断裂法',
  squareRootSegment: '平方根分段法',
  logarithmSegment: '对数分段法',
  customRange: '自定义分段',
  heatColor: '热点颜色',
  heatRadius: '热点半径',
  weightField: '权重字段',
  pixel: '像素',
  unSetting: '未设置',
  inputValueIsErroe: '输入值超出范围',
  filterErr: '查询条件有误',
  filterTip: '例如: id > 5',
  yaHei: '微软雅黑',
  simSun: '宋体',
  fangSong: '仿宋',
  simHei: '黑体',
  kaiTi: '楷体',
  arial: 'Arial',
  roman: 'Times-New-Roman',
  serif: 'Sans-serif',
  returnDeafult: '恢复默认',
  showCustomSingleValue: '展开',
  hideCustomSingleValue: '收起',
  customColor: '自定义颜色',
  hasNegValue: '数据中存在负数',
  hasZeroNegValue: '数据中存在负数或零',
  noSupportRange: '，不适合此分段方法',
  minRadius: '最小半径',
  maxRadius: '最大半径',
  customRadius: '自定义半径',
  customUniqueTip: '单击符号更改样式',
  customRangeTip: '单击符号和范围对符号样式和分段范围进行更改',
  customHeatTip: '单击色带更改热力图样式',
  customRankTip: '单击符号和范围对符号样式和分段范围进行更改',
  locationMode: '定位模式',
  coord: '按坐标',
  division: '按行政区划',
  fromXField: '起点X字段',
  fromYField: '起点Y字段',
  toXField: '终点X字段',
  toYField: '终点Y字段',
  fromCity: '起点字段',
  toCity: '终点字段',
  lineCurveness: '线曲率',
  fromLabelField: '起点名称字段',
  toLabelField: '终点名称字段',
  constantSpeed: '速度',
  baseSetting: '基本',
  animationSetting: '动画特效',
  symbolStyle: '样式',
  symbolSize: '大小',
  symbolSetting: '符号',
  outlineSetting: '轮廓',
  lineSetting: '线条',
  fillSetting: '填充',
  customSetting: '自定义',
  themeSetting: '专题',
  heatSetting: '热点',
  notSupportRange: '当前数据不支持制作分段专题图',
  colorType: '颜色方案',
  singleColor: '单色',
  multiColor: '多色',
  labelPosition: '布局',
  labelTextBaseline: '对齐基线',
  labelOutlineColor: '轮廓色',
  labelOutlineWidth: '轮廓宽度',
  labelByPoint: '点',
  labelByLine: '线',
  labelTextTop: '顶部',
  labelTextMiddle: '居中',
  labelTextBottom: '底部',
  pointOffsetX: 'X 偏移量',
  pointOffsetY: 'Y 偏移量',
  pointOffsetUnitTip: '单位：倍数。偏移距离为要素半径乘以倍数',

  //地图控制
  zoomIn: "放大",
  zoomOut: "缩小",
  visibleScaleChanged: '切换底图后，可能影响叠加图层的可见比例尺设置',

  //我的数据
  name: "名称",
  type: "类型",
  author: '作者',
  time: "更新时间",
  dataCount: '记录数',
  refreshData: "刷新数据",
  loading: "正在加载...",
  noDatas: "暂无数据",
  noSharedDatas: "暂无与我共享数据",
  sharePermissionData: '无权限添加此数据',
  downloadDataFaild: '获取共享数据失败',
  uploadShareDataFaild: '保存共享数据到我的数据失败',
  pointType: '点',
  lineType: '线',
  polygonType: '面',
  //poi
  searchCity: '搜索城市',
  searchLayers: '搜索图层',
  saveAll: '保存本页搜索结果',
  saveSelected: '保存所选',
  saveSearchFilter: '保存搜索条件',
  loadSearchFilter: '加载搜索条件',
  selectedAttr: '选择搜索字段',
  noResult: '无查询结果',
  noLayerNow: '暂无图层',
  noSearchFilter: '未设置查询条件',
  selectedSaveFeature: '请选择需要保存的要素',
  poiMarkerlayer: 'POI',
  nullAttribute: '无',
  selectedPOI: '请选中想要保存的记录',
  poiSaveSucceed: '保存成功',
  searchOnline: '搜索城市地点或图层',
  saveFilter: '保存并命名当前搜索条件',
  saveFilterSuccess: '保存搜索条件成功',
  loadFilter: '加载搜索条件',
  noFilter: '暂未保存过搜索条件',
  addressConfig: '需设置地址匹配服务，请联系管理员添加',
  inputFilterName: '请输入搜索条件的名称',
  exsitFilterName: '已经存在的搜索条件,请重新输入名字',
  useFilter: '使用已保存的搜索条件',
  filterName: '条件名称',
  createTime: '创建时间',
  matchSuccess: '搜索字段匹配成功',
  maxNameLength: '不超过20个字符',
  noSearchPermission: '操作无权限，请验证本地搜索服务key是否可用',
  restDataUrlError: '数据服务地址有误，请验证数据服务地址是否可用',
  noRestDataFields: '未检测到数据服务查询字段，请联系管理员配置',
  noOnlineSearchKey: '未检测到本地搜索服务key，请联系管理员配置',
  elasticsearchUrlError: 'Elasticsearch服务地址有误，请验证服务地址是否可用',
  elasticsearchCoordsError: '坐标字段有误，请验证坐标字段是否可用',
  addressMatchFaild: '地址匹配失败，请检查参数',

  //属性表
  dataNumber1: '（共计',
  dataNumber2: '个元素）',
  XYFieldIsNaN: 'X, Y坐标字段不是数字，请重新设置',


  // 文件上传
  unSupportFileType: '不支持的文件类型',
  dropUplod: '松开鼠标上传文件',
  chooseEncode: '选择文件编码格式',
  fileEncode: '文件编码格式',
  filter: '过滤',
  datas: '条数据',
  userCount: '(当前用户剩余次数：',
  loadend: '加载完成',
  iportalAddressNone: '(未配置地址匹配服务)',
  upLoadFileFailed: '上传文件失败',
  upLoadImageFailed: '上传图片失败',
  moveFileToDirFailed: '数据移动到在线制图文件夹失败',
  uploadRelationshipFaild: '上传到关系型数据库失败',
  publicServiceFaild: '发布服务失败',
  getDataServiceFaild: '获取服务失败',
  includePolygon: '请确认数据不包含线面几何集',
  includeMultiPolygon: '请确认数据不包含多线、多面',
  reasons: '可能的原因包括：',
  dataNumberOver: '1.文件数据量过多',
  checkRestDataConfig: '正在检查环境',
  unRestData: '环境检测未通过',
  getRestDataConfigFaild: '获取环境配置信息失败',
  uploadDataFaild: '文件上传失败',
  noServerAndRelationship: 'iPortal未配置托管服务器和关系型存储，无法上传数据',
  relationshipClose: '无法连接到关系型存储，请联系管理员配置',
  noHostServer: 'iPortal未配置托管服务器，无法上传数据',
  noRelationship: 'iPortal未配置关系型存储，无法上传数据',
  relationshipWrong: '3.关系型存储不可用',
  noPermissionUpload: '2.未登录',
  checkServer: '请检查服务器状态',
  uploadJsonFile: '上传失败，请检查数据内容是否符合GeoJSON数据规范',
  shareJsonFile: '不支持添加JSON数据',
  checkFileType: '检测文件类型',
  chooseOneData: '请选择一条数据',
  analyseData: '正在解析数据',
  getDataFaild: '获取我的数据失败',
  fieldIsNotString: '行政区划字段不是字符类型，请重新设置',
  matchFail的FromDivision: '按行政区划匹配失败，请检查匹配字段',
  PleaseSelectAssociationTable: "请选择一个关联表",
  disabledTableField: "不可用的关联表或关联字段",
  cannotGetFeature: "无法获取关联表的要素",
  associationFieldIncomplete: "关联字段配置不完整",
  //标注图层
  information: '信息',
  markerStyle: '样式',
  markerAttribute: '属性',
  applyToFeatures: '应用样式到全部标注',
  markerEdit: '标注编辑',
  markerLayerEdit: '图层编辑',
  textEdit: '文本标注',
  lineCap: '端点样式',
  polygonStrokeColor: '边线颜色',
  lineDash: '边线样式',
  polygonLineCap: '边线端点',
  polygonStrokeWidth: '边线宽度',
  polygonStrokeOpacity: '边线透明度',
  usePointSymbol: '使用点符号',
  usePointStyle: '使用点样式',
  pointRaduis: '点半径',
  sizeIsWrong: '请上传符合规范尺寸的图片',
  baseSymbol: '基础符号',
  moreSymbol: '更多符号',
  customSymbol: '自定义符号',
  uploadImg: '点击上传',
  custormSize: '支持SVG、JPG或PNG（最大50X50像素）',
  customImage: '建议上传图片不超过2M',
  local: '本地上传',
  network: '网络图片',
  urlIsWrong: '输入正确的url',
  otherUrl: '相关链接',
  videoUrl: '视频链接',
  notSupportVideo: "您的浏览器不支持该视频",
  bold: '加粗',
  italic: '倾斜',
  alignLeft: '左对齐',
  alignRight: '右对齐',
  alignCenter: '居中对齐',
  alignJustify: '两端对齐',
  contentIsNull: '请输入内容',
  font: '字体',
  fontSize: '字体大小',
  fontColor: '字体颜色',
  fontMaxWidth: '文本框最大宽度',
  backgroundColor: '背景颜色',
  widthIsWrong: '请输入数字',
  lessThanWidth: '输入的值低于可允许最小宽度：',
  //地图量算
  mapMeasure: "地图量算",
  distanceMeasure: "测距离",
  areaMeasure: "测面积",
  clearMeasure: "清除",
  clearCurrentMeasure: "清除量算结果",
  helpInfo: "单击左键添加点，双击结束",
  totalDistance: "总距离",
  totalArea: "总面积",
  startPoint: "起点",

  //分享页编辑按钮
  edit: "编辑",

  //全图
  zoomToExtent: "缩放至全图",
  graticuleOnOff: "经纬网",
  notSupportGraticule: "当前地图超出经纬网范围",
  showGraticule: "显示网格",
  gridIntervals: "网格间距",
  inputJustNumber: "请输入数字",
  inputMinNumber: "网格间距最小值为0.01度",
  inputMaxNumber: "网格间距最大值为90度",
  style: "网格样式",
  hiddenGraticule: "为提升渲染性能，当前级别下网格已隐藏，放大地图后可见",
  //路况
  traffic: '实时路况',
  trafficJam: '拥堵',
  trafficCrowding: '拥挤',
  trafficSlow: '缓行',
  trafficClear: '畅通',
  onlyAMapAndBMap: '路况仅在百度底图时可用',
  //鹰眼
  openOverViewMap: "打开鹰眼",
  closeOverViewMap: "关闭鹰眼",

  //更新图层
  updateDataFailed: "更新失败",
  isDifferentDataStructure: "更新数据与现有数据的结构不一致",
  updateModelContent: "请保证更新数据与现有数据的结构保持一致，更新有风险，是否继续？",

  //删除图层
  ModelTitle: "删除图层",
  ModelContent: "图层删除后无法恢复，是否删除？",
  ModelContinueButton: "继续",

  //地图标签
  noneMapTags: "暂无地图标签",
  addTags: "添加标签",
  tagLibrary: "标签库",
  useSelectedTags: "使用所选标签",
  tagLibraryTitle: "从列表中选中一个或多个标签",
  tagLibraryTitleTip: "（最多支持6个）",
  warnMessage: "最多支持6个标签",
  noTags: "暂无可用标签",
  tagRequestFail: "无法获取标签列表",
  defaultTag: '用户地图',

  //地图保存
  saveSucceed: '保存成功',
  saveFailed: '保存失败，服务器无响应',
  toBeRefresh: '，即将重新加载地图...',
  isSaving: '正在保存地图...',
  reloadMapFaild: '部分数据丢失',
  mapSave: '保存地图',
  mapSaveAs: '地图另存为',
  tagTips: '多个标签用逗号分隔，最多6个',
  noMapTitle: '请设置地图标题',
  noMapTags: '请设置地图标签',
  copy: '_副本',
  saveShareData: '该数据将被另存到',
  updateDataPermFaild: '更新数据权限失败',
  updateDataPermSuccess: '更新数据权限成功',
  dataSave: '保存数据',
  updateDataSuccess: '数据修改成功',
  confirmUpdateDataSave:"下列数据内容已被修改，请勾选需要保存修改的数据，未勾选的数据将在保存之后恢复：",
  //登录弹窗
  login: '登录',
  nameFormatIsWrong: '用户名输入错误',
  nameOrPassIsWrong: '用户名或密码错误',
  nameAndPassNotNull: "用户名或密码不能为空",
  loginSuccess: '登录成功',
  loginFaild: '登录失败',
  loadFaild: '加载失败',
  noEditPermission: '当前用户无权限访问该地图，请重新登录或联系管理员',

  //关于
  aboutDataVizTitle: "数据上图",
  aboutDataVizInfo: "基于 SuperMap iServer、iPortal 和 iClient 产品以及其他",
  openSourceSoftWare: "开源软件",
  openSourceProtocol: "开源协议",
  close: "关闭",
  protocol: "协议",
  homePage: "主页",

  //分享弹窗
  saveMapBefore: '请先保存地图，再进行分享',
  userName: '昵称或用户名',
  quotes: '：',
  noPermission: '您没有权限操作该地图',
  noPermission1: '暂无权限访问，请登录或联系管理员',
  noPermission2: '暂无此操作权限，请重新登录或联系管理员',
  noPermission3: '暂无此操作权限，请联系管理员',
  tips: '提示',
  newShow: '不再提示',
  notExistMap: "访问的地图不存在",
  noPermissionOr404: '您无权限访问该地图或该地图不存在',
  or:'或',
  create:'创建',
  createNewMap: '新地图',
  
  //引导图文
  guideModalTitle: '创建第一幅地图',
  guideModalDescription: '多种方式创建地图',
  addFromFileName: '数据文件上图',
  addFromFileDescription: '在地图上添加CSV、Excel、Shapefile等数据文件，一键制作专题图',
  addFromWebName: '服务上图',
  addFromWebDescription: '在地图上叠加SuperMap iServer发布的服务和OGC标准服务',
  addFromWebButton: '添加服务',
  addMarkerName: '绘制地图',
  addMarkerDescription: '在地图上绘制地图标注，并编辑位置、样式和描述信息',
  addMarkerButton: '绘制标注',
  donotShow: '不再显示',

  //地图加载
  getMapDataFaild: '部分数据丢失，地图加载异常',
  loadMapFaild: '地图加载失败',

  //图层不透明度
  opacity: '不透明度',
  layerOpacity: '图层不透明度',

  //图例
  legend: '图例',
  legendThemeField: '专题字段：',
  legendWeightField: '权重字段：',
  notSet: '未设置',
  rarely: '稀少',
  balanced: '均匀',
  crowded: '拥挤',

  //图层属性
  field: '字段',
  showOrHide: '显示/隐藏',
  isNumber: '数值',
  isText: '文本',
  media: "媒体",
  showHide: '显隐',
  enterTitle:"输入标题",
  enterUrl:"输入链接",
  video: "视频",
  addContent: "添加内容",
  addMedia: "添加媒体",
  addText: "添加文本",
  no: "暂无",
  mediaInfo: "媒体信息",
  popupInfoConfig: "弹窗配置",
  URL:"链接",
  editItem:"修改",
  setFieldShowOrHideTip:"设置字段显示和隐藏的功能已移至弹窗配置中",
  attributeModificationFailed:'属性信息修改失败',
  titleValueNotNull: "名称或链接不能为空",


  unsupportedCoordinateSystem: "不支持浏览和编辑该坐标系的地图",
  unsupportedServerType: "不支持的服务类型",
  unsupportedPreview: "当前的坐标系不支持预览",
  onlyBeViewedMap: "当前的坐标系不支持编辑",
  unsupportedEditMaker: "不支持修改共享地图中的标注图层",

  //地图属性气泡
  noField: "暂无图层属性",
  FieldsDisabled: "属性字段已隐藏",

  // 用户权限不够
  unPermission: "当前用户无保存数据权限，请联系管理员",
  userMap: "用户地图",

  // 点符号
  symbolCommon: '基本',
  symbolLifeService: '生活服务',
  symbolAnimalsAndPlants: '动植物',
  symbolBusiness: '商标',
  symbolNature: '自然',

  //iServer图层气泡
  selectIServerLayer: '请选择要查看的图层',
  querying: '正在获取信息...',
  queryFailed: '无法获取信息',
  noQueryResult: '没有可用的信息',

  noFilesSelected: "未选择任何文件",
  // 主题
  themeLight: '浅色',
  themeDark: '深色',
  themeDeveloping: '敬请期待',

  //Map Printing地图打印
  layoutTemplate: '布局模板',
  baseMapInfo: '基本信息',
  printing: '打印中', 
  subTitle: '副标题',
  copyRight: '版权信息',
  default: '默认',
  legendUrl: '图片URL',
  scaleText: '比例尺文本',
  textPosition: '文本位置',
  scaleLength: '段数',
  METER: '米',
  FOOT: '英尺',
  DEGREES: '度',
  centerPoint: '中心点',
  littleMap: '附图',
  exportFormat: '格式',
  OutputSettings: '导出选项',
  printUnavalibleWithLogin: '打印服务不可用,请',
  printUnavalible: '打印服务不可用 请联系管理员',
  printSuccess: '打印完成，正在下载打印结果',
  printOvertime: '请求超时，请重试',
  printFaild: '打印失败',
  overMaxDPI: '超过最大值',
  overMinDPI: '超出最小值',
  getCurrentLocal: '录入当前数据',
  printUnSupportLayer: '包含{layerType}无法打印',
  DATAFLOW_POINT_TRACK: '数据流图层',
  DATAFLOW_HEAT: '数据流热力图层',
  MAPBOXSTYLE: '矢量瓦片图层',
  MARKER: '标注图层',
  comma: '，',
  openLegend: '打印图例',
  printCurrentLegend: '打印当前图例',
  customPrintLegend: '自定义图例图片',
  upload: '上传',
  getSourceFaild:'获取失败',
  sourceNoPermission:'无权限',
  
  //页面语言资源
  DataVizHtml: {
    DataViz: '数据上图',
    loading: '正在加载...',
    legendTitle: '图例',
    back2Home: '返回首页',
    mapInfo:"地图信息",
    editBtn:"编辑",
  },

  //分享弹窗模块使用的语言资源
  shareWindow: {
    title: "标题",
    label: "标签",
    noLabel: "暂无标签",
    noDescription: "暂无描述",
    description: "描述",
    modalHeader: "分享权限",
    shareState: "分享状态",
    shareClose: "关闭分享",
    sharePublic: "公开分享",
    shareAuthoritySetting: "设置权限",
    shareAuthority: "指定权限",
    shareLink: "分享链接",
    shareIframe: "嵌入网页",
    getKeyFailed: "获取key失败",
    shareTo: "分享到",
    projectPermissionSettingSucceed: "地图权限设置成功",
    projectPermissionSettingFailed: "地图权限设置失败",
    copySuccess: "拷贝成功",
    copyFailed: "拷贝失败",
    userEntities: "用户",
    groupEntities: "群组",
    depEntities: "部门",
    getInfoFailed: "获取{xx}信息失败",
    searchEnableAll: "所有用户可检索",
    viewEnableAll: "所有用户可查看",
    editEnableAll: "所有用户可编辑（仅登录用户）",
    addRepeatedlyAll: "重复添加",
    nicknameOrUsername: "昵称或用户名",
    searchEnable: "可检索",
    viewEnable: "可查看",
    editEnable: "可编辑",
    addUser: "添加",
    clearUser: "清空",
    canNotAddYourself: "不能添加自己",
    canNotFindUser: "未查找到该用户",
    cancelButtonText: "取消",
    closeButtonText: "关闭",
    okButtonText: "确定",
    // 关联资源面板
    updateSourcesPermissionFailed: "关联资源权限更新失败",
    updateSourcesPermissionSucceed: "关联资源权限更新成功",
    getSourcesFailed: "关联资源获取失败",
    dataPermissionTip: "由于下列资源的共享方式与该地图不同，可能无法在共享后的地图中正常展示，为避免上述问题，您可以在下方选择要更新的资源。",
    otherUserData: "其他用户的资源",
    mySources: "我的资源",
    updatePermission: "更新权限",
    inputUserNameTip: "请输入用户名或昵称",
    name: "名称",
    type: "类型",
    owner: "所有者",
    datas: "数据",
    services: "服务",
    maps: "地图",
    updateSourcesPermission:"更新关联资源的权限",
    clickHere:"点这里"
},
  overViewMapCtrl: {
    //鹰眼
    openOverViewMap: "打开鹰眼",
    closeOverViewMap: "关闭鹰眼", 
  },
  //地图量算
  measureCtrl: {
    mapMeasure: "地图量算",
    distanceMeasure: "测距离",
    areaMeasure: "测面积",
    clearMeasure: "清除",
    clearCurrentMeasure: "清除量算结果",
    helpInfo: "单击左键添加点，双击结束",
    totalDistance: "总距离",
    totalArea: "总面积",
    startPoint: "起点"
  },

  outOfMaxExtent: '图形超出地图最大范围',
  remove: '移除'

};
